# The base image
FROM ubuntu:latest

# Install Python and pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

COPY server/requirements.txt .
    
# Install Python dependencies
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt
    
COPY server/ .

# Expose the port the app runs on
EXPOSE 8080

ENV FLASK_HOST=0.0.0.0
ENV FLASK_PORT=8080

CMD ["python3", "app.py"]