# The base image
FROM ubuntu:latest

WORKDIR /app

# Install Python and pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

    
    COPY server/ ./server
    
# Install Python dependencies
RUN pip install --no-cache-dir --break-system-packages -r server/requirements.txt

# Expose the port the app runs on
EXPOSE 8080

ENV FLASK_HOST=0.0.0.0
ENV FLASK_PORT=8080
ENV PYTHONPATH=/app

CMD ["python3", "server/app.py"]