# The base image
FROM python:3.11-alpine

WORKDIR /app

COPY server/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

COPY server/ ./server
    
# Expose the port the app runs on
EXPOSE 8080

ENV FLASK_HOST=0.0.0.0
ENV FLASK_PORT=8080
ENV PYTHONPATH=/app

CMD ["python3", "server/app.py"]